# Generated by Django 4.2.6 on 2023-10-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_casilleros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casillero",
            name="clave",
            field=models.IntegerField(default=1234, max_length=4),
        ),
    ]
