# Generated by Django 4.2.6 on 2023-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_casilleros", "0003_alter_casillero_clave"),
    ]

    operations = [
        migrations.AddField(
            model_name="casillero",
            name="abierto",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="casillero",
            name="disponible",
            field=models.CharField(
                choices=[
                    ("D", "Disponible"),
                    ("R", "Reservado"),
                    ("C", "Confirmado"),
                    ("A", "Cargado"),
                ],
                default="D",
                max_length=1,
            ),
        ),
    ]
