# Generated by Django 4.2.6 on 2023-11-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_casilleros", "0006_alter_casillero_r_email_alter_casillero_r_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="casillero",
            name="o_email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="casillero",
            name="o_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
