# Generated by Django 4.2.6 on 2023-11-26 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casilleros', '0008_rename_fecha_cancelacion_reserva_fecha_carga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casillero',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 19, 55, 54, 660819)),
        ),
    ]
