# Generated by Django 4.2.6 on 2023-11-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_casilleros", "0011_alter_casillero_fecha_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="casillero",
            name="estacion",
            field=models.IntegerField(default=0),
        ),
    ]
