# Generated by Django 4.2.6 on 2023-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casilleros', '0012_casillero_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bitacora',
            field=models.TextField(default=''),
        ),
    ]
